name: hell
version: 0
license: BSD3
author: "Chris Done"
copyright: "2023 Chris Done"

dependencies:
- base >= 4.17.2.1
- haskell-src-exts
- ghc-prim
- containers
- text
- bytestring
- async
- mtl
- directory
- syb
- constraints
- typed-process
- optparse-applicative
- hspec
- tagged
- QuickCheck
- template-haskell
- unliftio
- vector
- lucid2
- th-lift
- th-orphans
- aeson
- temporary

ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures
  - -O2

executables:
  hell:
    main: src/Hell.hs
    ghc-options:
      - -threaded
      - -rtsopts
