name: hell
version: 666.20250113
license: BSD3
author: "Chris Done"
copyright: "2023 Chris Done"
synopsis: "Haskell-based shell scripting language"
dependencies:
- base
- haskell-src-exts
- ghc-prim
- containers
- microlens
- text-zipper
- text
- bytestring
- async
- mtl
- directory
- syb
- constraints
- typed-process
- optparse-applicative
- hspec
- QuickCheck
- template-haskell
- unliftio
- vector
- lucid2
- th-lift
- th-orphans
- aeson
- temporary
- these
- vty
- vty-crossplatform
- brick
- generic-lens
- microlens-mtl
- deepseq

ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures
  - -O2

executables:
  hell:
    main: src/Hell.hs
    ghc-options:
      - -threaded
      - -rtsopts
