name: brossa
version: 0
license: BSD3
author: "Chris Done"
copyright: "2023 Chris Done"

dependencies:
- base >= 4.17.2.1
- haskell-src-exts
- ghc-prim
- containers
- text
- bytestring
- async
- mtl
- directory
- syb
- constraints
- typed-process
- optparse-applicative

executables:
  hell:
    main: Hell.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
