resolver: lts-21.24 # GHC-9.4.8
system-ghc: true
ghc-options:
  "$everything": "-split-sections -j"
packages:
- '.'
- reparsec

# extra-deps:
# - git: https://github.com/chrisdone/reparsec.git
#   commit: cb4ea16edbf1c72a3121723592d6785a65ba4115
