resolver: lts-21.24 # GHC-9.4.8
system-ghc: true
ghc-options:
  "$everything": "-split-sections -j"
packages:
- '.'
# - reparsec

extra-deps:
- git: https://github.com/chrisdone/reparsec.git
  commit: b2591d517edf131eb95ec19d83e2341d0d9dc882
