resolver: lts-21.24 # GHC-9.4.8
system-ghc: true
ghc-options:
  "$everything": "-split-sections -j"
packages:
- '.'
extra-deps:
- git: https://github.com/chrisdone/reparsec.git
  commit: 9fde10a583b50487564992e952b5b39ed987f573
